// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: track

#ifndef _TRACK_UI_COMP_H
#define _TRACK_UI_COMP_H

#ifdef __cplusplus
extern "C"
{
#endif

    lv_obj_t *ui_comp_get_child(lv_obj_t *comp, uint32_t child_idx);
    extern uint32_t LV_EVENT_GET_COMP_CHILD;

// COMPONENT statusBar
#define UI_COMP_STATUSBAR_STATUSBAR 0
#define UI_COMP_STATUSBAR_LABEL7 1
#define UI_COMP_STATUSBAR_LABEL8 2
#define _UI_COMP_STATUSBAR_NUM 3
    lv_obj_t *ui_statusBar_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
