// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: track

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C"
{
#endif

    extern uint8_t recState;
    extern char last_map_path[60];
    void ui_event_file(lv_event_t *e);
    void ui_rec_update(lv_event_t *e);
    void now_speed_call(lv_event_t *e);
    void onRecord(bool longPress);
    void set_text_statusBar(char *str);
    void rec_btn_style_set(lv_color_t bg_color, lv_color_t img_color, const void *img, lv_style_selector_t PART);
    void changeMap();
    void createPoint(uint8_t X, uint8_t Y);
    void ui_event_mapBtn(lv_event_t *e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
