// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: track

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C"
{
#endif

    void now_speed_call(lv_event_t *e);
    void Longitude_call(lv_event_t *e);
    void Latitude_call(lv_event_t *e);
    void Altitude_call(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
