// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: track

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void kmhAnim_Animation(lv_obj_t *TargetObject, int delay);
void btnsAnim_Animation(lv_obj_t *TargetObject, int delay);
lv_obj_t *ui_displayScr;
lv_obj_t *ui_Dial;
void ui_event_speed(lv_event_t *e);
lv_obj_t *ui_speed;
lv_obj_t *ui_kmh;
lv_obj_t *ui_AVG;
lv_obj_t *ui_Calorie;
lv_obj_t *ui_Trip;
lv_obj_t *ui_Time;
lv_obj_t *ui_menuBtn;
lv_obj_t *ui_timeData;
lv_obj_t *ui_avgData;
lv_obj_t *ui_calData;
lv_obj_t *ui_tripData;
lv_obj_t *ui_statusBar;
lv_obj_t *ui_btns;
lv_obj_t *ui_mapBtn;
void ui_event_statusBtn(lv_event_t *e);
lv_obj_t *ui_statusBtn;
void ui_event_menuBtn(lv_event_t *e);
lv_obj_t *ui_menuBtn;
void ui_event_sysInfo(lv_event_t *e);
lv_obj_t *ui_sysInfo;
lv_obj_t *ui_statusBar2;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_longitude;
lv_obj_t *ui_lonData;
lv_obj_t *ui_latitude;
lv_obj_t *ui_latData;
lv_obj_t *ui_altitude;
lv_obj_t *ui_altData;

void ui_event____initial_actions0(lv_event_t *e);
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void kmhAnim_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 800);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);
}
void btnsAnim_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 800);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, 100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_1);
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_speed(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        now_speed_call(e);
    }
}

void ui_event_statusBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_SHORT_CLICKED)
    {
        onRecord(false);
    }
    else if (event_code == LV_EVENT_LONG_PRESSED)
    {
        onRecord(true);
    }
    else if (event_code == LV_EVENT_KEY)
    {
        recState = 0;
        set_text_statusBar("error");
        rec_btn_style_set(lv_color_hex(0x2C2C2C), lv_color_hex(0xFBA414), &ui_img_m_start_png, LV_PART_MAIN);
        recorder.recInfo.cmd = RECORDER_CMD_STOP;
        xTimerStop(rec_timer, 0);
    }
}
void ui_event_menuBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(ui_sysInfo, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0);
    }
}
void ui_event_sysInfo(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM)
    {
        btnsAnim_Animation(ui_btns, 0);
        kmhAnim_Animation(ui_Dial, 0);
        _ui_state_modify(ui_menuBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_screen_change(ui_displayScr, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0);
    }
}
void ui_event____initial_actions0(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START)
    {
        kmhAnim_Animation(ui_Dial, 0);
        btnsAnim_Animation(ui_btns, 0);
    }
}

///////////////////// SCREENS ////////////////////
void ui_displayScr_screen_init(void)
{
    ui_displayScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_displayScr, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_displayScr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_displayScr, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Dial = lv_obj_create(ui_displayScr);
    lv_obj_set_width(ui_Dial, 240);
    lv_obj_set_height(ui_Dial, 140);
    lv_obj_set_x(ui_Dial, 0);
    lv_obj_set_y(ui_Dial, -21);
    lv_obj_set_align(ui_Dial, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Dial, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Dial, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dial, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Dial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed = lv_label_create(ui_Dial);
    lv_obj_set_width(ui_speed, LV_SIZE_CONTENT);  /// 2
    lv_obj_set_height(ui_speed, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_speed, 0);
    lv_obj_set_y(ui_speed, 10);
    lv_obj_set_align(ui_speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed, "00");
    lv_obj_set_style_text_font(ui_speed, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmh = lv_label_create(ui_Dial);
    lv_obj_set_width(ui_kmh, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_kmh, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_kmh, 0);
    lv_obj_set_y(ui_kmh, 45);
    lv_obj_set_align(ui_kmh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmh, "Km/h");
    lv_obj_set_style_text_color(ui_kmh, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kmh, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AVG = lv_label_create(ui_displayScr);
    lv_obj_set_width(ui_AVG, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_AVG, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_AVG, -60);
    lv_obj_set_y(ui_AVG, 0);
    lv_obj_set_align(ui_AVG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AVG, "AVG");

    ui_Calorie = lv_label_create(ui_displayScr);
    lv_obj_set_width(ui_Calorie, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Calorie, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Calorie, 60);
    lv_obj_set_y(ui_Calorie, 55);
    lv_obj_set_align(ui_Calorie, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Calorie, "Calorie");

    ui_Trip = lv_label_create(ui_displayScr);
    lv_obj_set_width(ui_Trip, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Trip, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Trip, -60);
    lv_obj_set_y(ui_Trip, 55);
    lv_obj_set_align(ui_Trip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Trip, "Trip");

    ui_Time = lv_label_create(ui_displayScr);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Time, 60);
    lv_obj_set_y(ui_Time, 0);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "Time");

    ui_timeData = lv_label_create(ui_displayScr);
    lv_obj_set_width(ui_timeData, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_timeData, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_timeData, 58);
    lv_obj_set_y(ui_timeData, -19);
    lv_obj_set_align(ui_timeData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeData, "00:00");
    lv_obj_set_style_text_color(ui_timeData, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_avgData = lv_label_create(ui_displayScr);
    lv_obj_set_width(ui_avgData, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_avgData, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_avgData, -58);
    lv_obj_set_y(ui_avgData, -19);
    lv_obj_set_align(ui_avgData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_avgData, "00 km/h");
    lv_obj_set_style_text_color(ui_avgData, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_avgData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calData = lv_label_create(ui_displayScr);
    lv_obj_set_width(ui_calData, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_calData, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_calData, 58);
    lv_obj_set_y(ui_calData, 36);
    lv_obj_set_align(ui_calData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_calData, "0 k");
    lv_obj_set_style_text_color(ui_calData, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_calData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tripData = lv_label_create(ui_displayScr);
    lv_obj_set_width(ui_tripData, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tripData, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tripData, -58);
    lv_obj_set_y(ui_tripData, 36);
    lv_obj_set_align(ui_tripData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tripData, "00 km");
    lv_obj_set_style_text_color(ui_tripData, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tripData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusBar = ui_statusBar_create(ui_displayScr);
    lv_obj_set_x(ui_statusBar, 0);
    lv_obj_set_y(ui_statusBar, -152);
    lv_obj_set_style_radius(ui_statusBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusBar, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btns = lv_obj_create(ui_displayScr);
    lv_obj_set_width(ui_btns, 227);
    lv_obj_set_height(ui_btns, 63);
    lv_obj_set_x(ui_btns, 0);
    lv_obj_set_y(ui_btns, 110);
    lv_obj_set_align(ui_btns, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btns, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btns, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_btns, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_btns, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btns, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btns, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_btns, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_btns, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_btns, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_btns, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mapBtn = lv_btn_create(ui_btns);
    lv_obj_set_width(ui_mapBtn, 50);
    lv_obj_set_height(ui_mapBtn, 40);
    lv_obj_set_x(ui_mapBtn, -71);
    lv_obj_set_y(ui_mapBtn, 107);
    lv_obj_set_align(ui_mapBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_mapBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_mapBtn, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_mapBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_mapBtn, LV_OBJ_FLAG_SCROLLABLE);                            /// Flags
    lv_obj_set_scrollbar_mode(ui_mapBtn, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_mapBtn, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mapBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mapBtn, &ui_img_map_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_mapBtn, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_mapBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mapBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_mapBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_mapBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mapBtn, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_mapBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_mapBtn, &ui_img_map_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_mapBtn, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_mapBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_mapBtn, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_mapBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(ui_mapBtn, &ui_img_map_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_mapBtn, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_mapBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_statusBtn = lv_btn_create(ui_btns);
    lv_obj_set_width(ui_statusBtn, 50);
    lv_obj_set_height(ui_statusBtn, 40);
    lv_obj_set_x(ui_statusBtn, 0);
    lv_obj_set_y(ui_statusBtn, 107);
    lv_obj_set_align(ui_statusBtn, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_statusBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    // lv_obj_clear_flag(ui_statusBtn, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_statusBtn, lv_color_hex(0x2C2C2C), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_statusBtn, 255, LV_PART_MAIN);
    lv_obj_set_style_bg_img_src(ui_statusBtn, &ui_img_m_start_png, LV_PART_MAIN);
    lv_obj_set_style_bg_img_recolor(ui_statusBtn, lv_color_hex(0xFBA414), LV_PART_MAIN);
    lv_obj_set_style_bg_img_recolor_opa(ui_statusBtn, 255, LV_PART_MAIN);
    // lv_obj_set_style_bg_color(ui_statusBtn, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_CHECKED);
    // lv_obj_set_style_bg_opa(ui_statusBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    // lv_obj_set_style_bg_img_src(ui_statusBtn, &ui_img_m_stop_png, LV_PART_MAIN | LV_STATE_CHECKED);
    // lv_obj_set_style_bg_img_recolor(ui_statusBtn, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_CHECKED);
    // lv_obj_set_style_bg_img_recolor_opa(ui_statusBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    // lv_obj_set_style_bg_color(ui_statusBtn, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_bg_opa(ui_statusBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_bg_img_src(ui_statusBtn, &ui_img_m_stop_png, LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_bg_img_recolor(ui_statusBtn, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_bg_img_recolor_opa(ui_statusBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    // lv_obj_set_style_bg_color(ui_statusBtn, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    // lv_obj_set_style_bg_opa(ui_statusBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_menuBtn = lv_btn_create(ui_btns);
    lv_obj_set_width(ui_menuBtn, 50);
    lv_obj_set_height(ui_menuBtn, 40);
    lv_obj_set_x(ui_menuBtn, 97);
    lv_obj_set_y(ui_menuBtn, 103);
    lv_obj_set_align(ui_menuBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_menuBtn, LV_OBJ_FLAG_SCROLLABLE);                            /// Flags
    lv_obj_set_style_radius(ui_menuBtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menuBtn, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menuBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menuBtn, &ui_img_m_menu_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_menuBtn, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_menuBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menuBtn, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_menuBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_menuBtn, &ui_img_m_menu_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_menuBtn, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_menuBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_menuBtn, lv_color_hex(0xFBA414), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_menuBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(ui_menuBtn, &ui_img_m_menu_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_menuBtn, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_menuBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_speed, ui_event_speed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_statusBtn, ui_event_statusBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuBtn, ui_event_menuBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeData, ui_rec_update, LV_EVENT_ALL, NULL);
}
void ui_sysInfo_screen_init(void)
{
    ui_sysInfo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sysInfo, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_statusBar2 = ui_statusBar_create(ui_sysInfo);
    lv_obj_set_x(ui_statusBar2, 0);
    lv_obj_set_y(ui_statusBar2, -152);

    ui_Panel2 = lv_obj_create(ui_sysInfo);
    lv_obj_set_width(ui_Panel2, 199);
    lv_obj_set_height(ui_Panel2, 273);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 5);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_longitude = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_longitude, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_longitude, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_longitude, 25);
    lv_obj_set_y(ui_longitude, -85);
    lv_obj_set_align(ui_longitude, LV_ALIGN_CENTER);
    lv_label_set_text(ui_longitude, "Longitude");

    ui_lonData = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lonData, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lonData, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_lonData, -63);
    lv_obj_set_y(ui_lonData, -88);
    lv_obj_set_align(ui_lonData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lonData, "xxxxxxxx");

    ui_latitude = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_latitude, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_latitude, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_latitude, 25);
    lv_obj_set_y(ui_latitude, 26);
    lv_obj_set_align(ui_latitude, LV_ALIGN_CENTER);
    lv_label_set_text(ui_latitude, "Latitude");

    ui_latData = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_latData, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_latData, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_latData, -48);
    lv_obj_set_y(ui_latData, -30);
    lv_obj_set_align(ui_latData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_latData, "xxxxxxxx");

    ui_altitude = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_altitude, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_altitude, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_altitude, LV_ALIGN_CENTER);
    lv_label_set_text(ui_altitude, "Altitude");

    ui_altData = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_altData, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_altData, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_altData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_altData, "0m");

    lv_obj_add_event_cb(ui_sysInfo, ui_event_sysInfo, LV_EVENT_ALL, NULL);
}

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_displayScr_screen_init();
    ui_sysInfo_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_displayScr);
}
