// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: track

#include "ui.h"

void ui_comp_statusBar_create_hook( lv_obj_t * comp)
{
}
