// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: track

#include "ui.h"
#include "nmea_parser.h"
#include <stdio.h>
#include <stdlib.h>
#include "gpx_rec.h"
#include "convert_lat_lng.h"

#define STRLEN 20

static const char *TAG = "ui_event";
uint8_t recState = 0;
float last_lng = 0;
float last_lat = 0;
uint32_t last_time = 0;
double Total_trip = 0;

char last_map_path[60] = "";

// uint32_t get_time(gps_t *gps)
// {
//     long totalSeconds = gps->tim.hour * 3600 + gps->tim.minute * 60 + gps->tim.second;
//     long totalDays = gps->date.day;
//     return (totalSeconds + (totalDays * 24 * 3600));
// }

float getSpeed(gps_t *gps)
{
    if (gps->valid == false)
    {
        return 0;
    }
    if (last_lng == 0 || last_lat == 0)
    {
        last_lng = gps->longitude;
        last_lat = gps->latitude;
        last_time = recorder.recInfo.time;
        return 0;
    }
    float lng = gps->longitude;
    float lat = gps->latitude;
    double distance = getDistance(lng, lat, last_lng, last_lat);
    last_lng = lng;
    last_lat = lat;
    uint32_t now_time = recorder.recInfo.time;
    float speedKmh = (distance / (now_time - last_time)) * 3.6;
    last_time = now_time;

    if (gpsInfo.speed > 0)
    {
        if (recorder.active == true)
        {
            Total_trip += distance;
        }
        return speedKmh;
    }
    else
    {
        return gps->speed;
    }
}

void ui_event_file(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        char file[20] = "";
        lv_dropdown_get_selected_str(ui_history, file, sizeof(file));
        ESP_LOGI(TAG, "%s", file);
    }
}
void now_speed_call(lv_event_t *e)
{
    gps_t *gps = (gps_t *)lv_event_get_param(e);
    char str[STRLEN];

    if (gps != NULL)
    {
        lv_label_set_text_fmt(ui_dayData, "%d-%02d-%02d", gps->date.year + YEAR_BASE, gps->date.month, gps->date.day);
        if (recorder.active == true)
        {
            getSpeed(gps);
            // lv_label_set_text_fmt(ui_speed, "%02d", (uint8_t)getSpeed(gps));
            lv_label_set_text_fmt(ui_speed, "%02d", (int)(gps->speed * 3.6));
        }
        else
        {
            lv_label_set_text(ui_speed, "00");
        }

        lv_label_set_text_fmt(ui_comp_get_child(ui_statusBar, UI_COMP_STATUSBAR_LABEL7), "%02d : %02d", gps->tim.hour + TIME_ZONE, gps->tim.minute);
        lv_label_set_text_fmt(ui_comp_get_child(ui_statusBar2, UI_COMP_STATUSBAR_LABEL7), "%02d : %02d", gps->tim.hour + TIME_ZONE, gps->tim.minute);

        snprintf(str, sizeof(str), "%.05f", gps->latitude);
        lv_label_set_text_fmt(ui_latData, "%s", str);

        snprintf(str, 5, "%d", (int)gps->altitude);
        lv_label_set_text_fmt(ui_altData, "%sm", str);

        snprintf(str, sizeof(str), "%.05f", gps->longitude);
        lv_label_set_text_fmt(ui_lonData, "%s", str);

        snprintf(str, sizeof(str), "%.1f", gps->dop_h);
        lv_label_set_text_fmt(ui_hor_dilData, "%s", str);

        snprintf(str, sizeof(str), "%.03f", gps->cog);
        lv_label_set_text_fmt(ui_gps_valData, "%s", str);
        lv_label_set_text_fmt(ui_sateData, "%d / %d", gps->sats_in_use, gps->sats_in_view);
    }
}

void rec_btn_style_set(lv_color_t bg_color, lv_color_t img_color, const void *img, lv_style_selector_t PART)
{
    lv_obj_set_style_bg_color(ui_statusBtn, bg_color, PART);
    lv_obj_set_style_bg_opa(ui_statusBtn, 255, PART);
    lv_obj_set_style_bg_img_src(ui_statusBtn, img, PART);
    lv_obj_set_style_bg_img_recolor(ui_statusBtn, img_color, PART);
    lv_obj_set_style_bg_img_recolor_opa(ui_statusBtn, 255, PART);
}
void set_text_statusBar(char *str)
{
    lv_label_set_text(ui_comp_get_child(ui_statusBar, UI_COMP_STATUSBAR_LABEL8), str);
    lv_label_set_text(ui_comp_get_child(ui_statusBar2, UI_COMP_STATUSBAR_LABEL8), str);
}

void ui_rec_update(lv_event_t *e)
{
    Recorder_Info_t Info = recorder.recInfo;
    lv_event_code_t event_code = lv_event_get_code(e);
    static float last_speed = 0;
    char str[20];
    int hour, min, sec;
    double trip = 0;
    if (LV_EVENT_VALUE_CHANGED == event_code)
    {
        last_speed = (float)atoi(lv_label_get_text(ui_speed));

        last_speed = (Info.avg_speed * (Info.time - 1) + last_speed) / Info.time;
        recorder.recInfo.avg_speed = last_speed;
        snprintf(str, sizeof(str), "%.01f", Info.avg_speed);
        lv_label_set_text_fmt(ui_avgData, "%skm/h", str);

        hour = Info.time / 3600;       // 计算小时数
        min = (Info.time % 3600) / 60; // 计算剩余分钟数
        sec = Info.time % 60;          // 计算剩余秒数
        if (hour > 0)
        {
            snprintf(str, sizeof(str), "%d: %02d: %02d", hour, min, sec);
        }
        else
        {
            snprintf(str, sizeof(str), "%02d: %02d", min, sec);
        }
        lv_label_set_text_fmt(ui_timeData, "%s", str);

        trip = Total_trip; // 计算路程
        if (trip > 1000)
        {
            snprintf(str, sizeof(str), "%.02f km", trip / 1000);
        }
        else
        {
            snprintf(str, sizeof(str), "%d m", (int)trip);
        }
        lv_label_set_text_fmt(ui_tripData, "%s", str);
    }
}
void onRecord(bool longPress)
{
    switch (recState)
    {
    case 0: // 空闲
        if (!longPress)
        {
            recState = 1;
            set_text_statusBar("REC");
            rec_btn_style_set(lv_color_hex(0xFBA414), lv_color_hex(0x2C2C2C), &ui_img_m_stop_png, LV_PART_MAIN);
            recorder.recInfo.cmd = RECORDER_CMD_START;
            xTimerReset(rec_timer, 0);
        }
        break;
    case 1: // 记录
        if (!longPress)
        {
            recState = 2;
            set_text_statusBar("PUASE");
            rec_btn_style_set(lv_color_hex(0xFBA414), lv_color_hex(0x2C2C2C), &ui_img_m_start_png, LV_PART_MAIN);
            recorder.recInfo.cmd = RECORDER_CMD_PAUSE;
            recorder.active = false;
            xTimerStop(rec_timer, 0);
        }
        break;
    case 2: // 暂停
        if (!longPress)
        {
            recState = 1;
            set_text_statusBar("REC");
            rec_btn_style_set(lv_color_hex(0xFBA414), lv_color_hex(0x2C2C2C), &ui_img_m_stop_png, LV_PART_MAIN);
            recorder.recInfo.cmd = RECORDER_CMD_CONTINUE;
            recorder.active = true;
            xTimerStart(rec_timer, 0);
        }
        else
        {
            recState = 0;
            set_text_statusBar("");
            rec_btn_style_set(lv_color_hex(0x2C2C2C), lv_color_hex(0xFBA414), &ui_img_m_start_png, LV_PART_MAIN);
            recorder.recInfo.cmd = RECORDER_CMD_STOP;
            xTimerStop(rec_timer, 0);
        }
        break;
    default:
        break;
    }
}
#define MAP_Path "/sdcard/map_nor_gcj02"

void createPoint(uint8_t mapX, uint8_t mapY)
{
    lv_obj_clear_flag(ui_mapPoint, LV_OBJ_FLAG_HIDDEN);
    if (mapX >= 230)
    {
        lv_img_set_offset_x(ui_map, 240 - 256);
        lv_obj_set_x(ui_mapPoint, mapX + (240 - 256));
    }
    else
    {
        lv_obj_set_x(ui_mapPoint, mapX);
    }
    if (mapY >= 230)
    {
        lv_img_set_offset_y(ui_map, 240 - 256);
        lv_obj_set_y(ui_mapPoint, mapY + (240 - 256));
    }
    else
    {
        lv_obj_set_y(ui_mapPoint, mapY);
    }
}

void changeMap()
{
    float lonData;
    float latData;
    char filePath[60];
    // static float last_lng, last_lat;
    if (gpsInfo.valid)
    {
        latData = gpsInfo.latitude;
        lonData = gpsInfo.longitude;
        wgs84_to_gcj02(&lonData, &latData);
        printf("lng = %f, lat = %f\n", lonData, latData);
        uint32_t PixelX, PixelY;
        uint32_t tileX, tileY;
        uint8_t zoom = 14;
        LatLongToPixelXY(latData, lonData, zoom, &PixelX, &PixelY);
        uint8_t tileSubX, tileSubY;
        uint8_t pixelSubX = 0, pixelSubY = 0;
        PixelXYToTileXY(PixelX, PixelY, 256, 256, &tileX, &tileY, &tileSubX, &tileSubY, &pixelSubX, &pixelSubY);
        snprintf(filePath, sizeof(filePath), MAP_Path "/%d/%d/%d.bin", zoom, tileX, tileY);
        if (strlen(last_map_path) == 0 || strcmp(last_map_path, filePath) != 0)
        {
            printf("%s\n", filePath);
            lv_img_set_bin_src(filePath);
            strcpy(last_map_path, filePath);
        }
        createPoint(pixelSubX, pixelSubY);
    }
    else
    {
        lv_obj_add_flag(ui_mapPoint, LV_OBJ_FLAG_HIDDEN);
        lv_img_set_bin_src(MAP_Path "/3/6/3.bin");
    }
}

void ui_event_mapBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        // char *files = get_gpx_fileName();
        // printf("%s\n", files);
        // lv_dropdown_set_options(ui_history, files);
        // free(files);
        changeMap();
        _ui_screen_change(ui_mapScr, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0);
        ui_now_scr = UI_MAP_SCR;
    }
}